/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controller.CategoriaController;
import controller.LibroController;
import controller.UsuarioController;
import controller.PrestamoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Libro;
import model.Categoria;
import model.Usuario;
import model.Prestamo;


public class LibroView extends javax.swing.JPanel {

    /**
     * Creates new form LibroView
     */
    public LibroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel29 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacategorias = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        crearcategoria = new javax.swing.JButton();
        actualizarcategoria = new javax.swing.JButton();
        leercategoria = new javax.swing.JButton();
        eliminarcategoria = new javax.swing.JButton();
        idcategoriafield = new javax.swing.JTextField();
        nombrecategoriafield = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalibros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        crearlibro = new javax.swing.JButton();
        actualizarlibro = new javax.swing.JButton();
        leerlibro = new javax.swing.JButton();
        eliminarlibro = new javax.swing.JButton();
        idlibrofield = new javax.swing.JTextField();
        editoriallibrofield = new javax.swing.JTextField();
        titulolibrofield = new javax.swing.JTextField();
        autorlibrofield = new javax.swing.JTextField();
        añolibrofield = new javax.swing.JTextField();
        isbnlibrofield = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        crearusuario = new javax.swing.JButton();
        actualizarusuarios = new javax.swing.JButton();
        leerusuarios = new javax.swing.JButton();
        eliminarusuarios = new javax.swing.JButton();
        idusuariofield = new javax.swing.JTextField();
        telefonousuariofield = new javax.swing.JTextField();
        nombreusuariofield = new javax.swing.JTextField();
        emailusuariofield = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablausuarios = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaprestamos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        crearprestamo = new javax.swing.JButton();
        actualizarprestamo = new javax.swing.JButton();
        leerprestamos = new javax.swing.JButton();
        eliminarprestamo = new javax.swing.JButton();
        Idprestamofield = new javax.swing.JTextField();
        fechaprestamofield = new javax.swing.JTextField();
        idlibroprestamofield = new javax.swing.JTextField();
        idusuarioprestamofield = new javax.swing.JTextField();
        fechadevolucionfield = new javax.swing.JTextField();

        jLabel29.setText("TEXT FIELD");

        tablacategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Categoria", "Nombre categoria"
            }
        ));
        jScrollPane2.setViewportView(tablacategorias);

        jLabel9.setText("Nombre categoria");

        jLabel10.setText("ID Categoria");

        crearcategoria.setText("Crear categoria");
        crearcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearcategoriaActionPerformed(evt);
            }
        });

        actualizarcategoria.setText("Actualizar categoria");
        actualizarcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarcategoriaActionPerformed(evt);
            }
        });

        leercategoria.setText("Leer categoria");
        leercategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leercategoriaActionPerformed(evt);
            }
        });

        eliminarcategoria.setText("Eliminar categoria");
        eliminarcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcategoriaActionPerformed(evt);
            }
        });

        nombrecategoriafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecategoriafieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crearcategoria)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nombrecategoriafield, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(leercategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizarcategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarcategoria))
                    .addComponent(idcategoriafield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(idcategoriafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nombrecategoriafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearcategoria)
                    .addComponent(leercategoria)
                    .addComponent(actualizarcategoria)
                    .addComponent(eliminarcategoria))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1153, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Categorias", jPanel2);

        tablalibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id libro", "Título", "Autor", "Editorial", "Año publicación", "Isbn"
            }
        ));
        jScrollPane1.setViewportView(tablalibros);
        if (tablalibros.getColumnModel().getColumnCount() > 0) {
            tablalibros.getColumnModel().getColumn(5).setHeaderValue("Isbn");
        }

        jLabel1.setText("Editorial");

        jLabel2.setText("Autor");

        jLabel3.setText("Título");

        jLabel4.setText("Id libro");

        jLabel5.setText("Año publicación");

        jLabel6.setText("Isbn");

        crearlibro.setText("Crear libro");
        crearlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearlibroActionPerformed(evt);
            }
        });

        actualizarlibro.setText("Actualizar libro");
        actualizarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarlibroActionPerformed(evt);
            }
        });

        leerlibro.setText("Leer libro");
        leerlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerlibroActionPerformed(evt);
            }
        });

        eliminarlibro.setText("Eliminar libro");
        eliminarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarlibroActionPerformed(evt);
            }
        });

        isbnlibrofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnlibrofieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crearlibro)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(leerlibro)
                        .addGap(45, 45, 45)
                        .addComponent(actualizarlibro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarlibro))
                    .addComponent(idlibrofield)
                    .addComponent(titulolibrofield)
                    .addComponent(autorlibrofield)
                    .addComponent(editoriallibrofield)
                    .addComponent(añolibrofield)
                    .addComponent(isbnlibrofield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idlibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(titulolibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(autorlibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(editoriallibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(añolibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isbnlibrofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crearlibro)
                            .addComponent(leerlibro)
                            .addComponent(actualizarlibro)
                            .addComponent(eliminarlibro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Libros", jPanel1);

        jLabel15.setText("Telefono");

        jLabel16.setText("Email");

        jLabel17.setText("Nombre");

        jLabel18.setText("Id usuario");

        crearusuario.setText("Crear usuario");
        crearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearusuarioActionPerformed(evt);
            }
        });

        actualizarusuarios.setText("Actualizar usuario");
        actualizarusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarusuariosActionPerformed(evt);
            }
        });

        leerusuarios.setText("Leer usuarios");
        leerusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerusuariosActionPerformed(evt);
            }
        });

        eliminarusuarios.setText("Eliminar usuario");
        eliminarusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarusuariosActionPerformed(evt);
            }
        });

        idusuariofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idusuariofieldActionPerformed(evt);
            }
        });

        telefonousuariofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonousuariofieldActionPerformed(evt);
            }
        });

        tablausuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id usuario", "Nombre", "Email", "Telefono"
            }
        ));
        jScrollPane4.setViewportView(tablausuarios);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idusuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreusuariofield))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailusuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(telefonousuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(crearusuario)
                        .addGap(22, 22, 22)
                        .addComponent(leerusuarios)
                        .addGap(25, 25, 25)
                        .addComponent(actualizarusuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarusuarios)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(idusuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(nombreusuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(emailusuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(telefonousuariofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearusuario)
                    .addComponent(leerusuarios)
                    .addComponent(actualizarusuarios)
                    .addComponent(eliminarusuarios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Usuarios", jPanel4);

        tablaprestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id prestamo", "Id libro", "Id usuario", "Fecha prestamo", "Fecha devolución"
            }
        ));
        jScrollPane3.setViewportView(tablaprestamos);

        jLabel7.setText("Fecha prestamo");

        jLabel8.setText("Id usuario");

        jLabel11.setText("Id libro");

        jLabel12.setText("Id prestamo");

        jLabel13.setText("Fecha devolución");

        crearprestamo.setText("Crear prestamo");
        crearprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearprestamoActionPerformed(evt);
            }
        });

        actualizarprestamo.setText("Actualizar prestamo");
        actualizarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarprestamoActionPerformed(evt);
            }
        });

        leerprestamos.setText("Leer prestamos");
        leerprestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerprestamosActionPerformed(evt);
            }
        });

        eliminarprestamo.setText("Eliminar prestamo");
        eliminarprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarprestamoActionPerformed(evt);
            }
        });

        Idprestamofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdprestamofieldActionPerformed(evt);
            }
        });

        idusuarioprestamofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idusuarioprestamofieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearprestamo))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fechaprestamofield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addComponent(idusuarioprestamofield, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idlibroprestamofield, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Idprestamofield, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fechadevolucionfield))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(leerprestamos)
                        .addGap(18, 18, 18)
                        .addComponent(actualizarprestamo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarprestamo)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Idprestamofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(idlibroprestamofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idusuarioprestamofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fechaprestamofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechadevolucionfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearprestamo)
                    .addComponent(leerprestamos)
                    .addComponent(actualizarprestamo)
                    .addComponent(eliminarprestamo))
                .addGap(58, 58, 58))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Prestamos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarlibroActionPerformed
        LibroController libro= new LibroController();
        libro.eliminarLibro(Integer.parseInt(idlibrofield.getText()));
    }//GEN-LAST:event_eliminarlibroActionPerformed

    private void leerlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerlibroActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablalibros.getModel();
        model.setRowCount(0);
        ArrayList<Libro> libros = new ArrayList();
        LibroController libro = new LibroController();
        List<Libro> leer = libro.leerLibros();
        libros.addAll(leer);

        Object columnas[] = new Object[6];
        for(Libro c : libros){
            columnas[0]=c.getId_libro();
            columnas [1]=c.getTitulo();
            columnas [2]=c.getAutor();
            columnas [3]=c.getEditorial();
            columnas [4]=c.getAnio_publicacion();
            columnas [5]=c.getIsbn();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_leerlibroActionPerformed

    private void actualizarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarlibroActionPerformed
        LibroController libro= new LibroController();
        libro.actualizarLibros(Integer.parseInt(idlibrofield.getText()), titulolibrofield.getText(), autorlibrofield.getText(), editoriallibrofield.getText(), Integer.parseInt(añolibrofield.getText()), isbnlibrofield.getText());
    }//GEN-LAST:event_actualizarlibroActionPerformed

    private void crearlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearlibroActionPerformed
        LibroController libro= new LibroController();
        libro.crearLibro(titulolibrofield.getText(), autorlibrofield.getText(), editoriallibrofield.getText(), Integer.parseInt(añolibrofield.getText()), isbnlibrofield.getText());
    }//GEN-LAST:event_crearlibroActionPerformed

    private void nombrecategoriafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecategoriafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecategoriafieldActionPerformed

    private void eliminarcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcategoriaActionPerformed
        CategoriaController categoria= new CategoriaController();
        categoria.eliminarCategoria(Integer.parseInt(idcategoriafield.getText()));
    }//GEN-LAST:event_eliminarcategoriaActionPerformed

    private void leercategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leercategoriaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablacategorias.getModel();
        model.setRowCount(0);
        ArrayList<Categoria> categorias = new ArrayList();
        CategoriaController categoria = new CategoriaController();
        List<Categoria> leer = categoria.leerCategorias();
        categorias.addAll(leer);

        Object columnas[] = new Object[2];
        for(Categoria c : categorias){
            columnas[0]=c.getCategoria_id();
            columnas [1]=c.getNombre();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_leercategoriaActionPerformed

    private void actualizarcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarcategoriaActionPerformed
        CategoriaController categoria= new CategoriaController();
        categoria.actualizarCategoria(Integer.parseInt(idcategoriafield.getText()), nombrecategoriafield.getText());
    }//GEN-LAST:event_actualizarcategoriaActionPerformed

    private void crearcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearcategoriaActionPerformed
        CategoriaController categoria= new CategoriaController();
        categoria.crearCategoria(nombrecategoriafield.getText());
    }//GEN-LAST:event_crearcategoriaActionPerformed

    private void crearprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearprestamoActionPerformed
        PrestamoController prestamo= new PrestamoController();
        prestamo.crearPrestamo(Integer.parseInt(idlibroprestamofield.getText()), Integer.parseInt(idusuarioprestamofield.getText()), fechaprestamofield.getText(), fechadevolucionfield.getText());
    }//GEN-LAST:event_crearprestamoActionPerformed

    private void actualizarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarprestamoActionPerformed
        PrestamoController prestamo= new PrestamoController();
        prestamo.actualizarPrestamo(Integer.parseInt(Idprestamofield.getText()), Integer.parseInt(idlibroprestamofield.getText()), Integer.parseInt(idusuarioprestamofield.getText()), fechaprestamofield.getText(), fechadevolucionfield.getText());
    }//GEN-LAST:event_actualizarprestamoActionPerformed

    private void leerprestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerprestamosActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaprestamos.getModel();
        model.setRowCount(0);
        ArrayList<Prestamo> prestamos = new ArrayList();
        PrestamoController prestamo = new PrestamoController();
        List<Prestamo> leer = prestamo.leerPrestamos();
        prestamos.addAll(leer);

        Object columnas[] = new Object[5];
        for(Prestamo c : prestamos){
            columnas[0]=c.getId_prestamo();
            columnas [1]=c.getId_libroprestamo();
            columnas[2]=c.getId_usuarioprestamo();
            columnas [3]=c.getFecha_prestamo();
            columnas[4]=c.getFecha_devolucion();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_leerprestamosActionPerformed

    private void eliminarprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarprestamoActionPerformed
        PrestamoController prestamo= new PrestamoController();
        prestamo.eliminarPrestamo(Integer.parseInt(Idprestamofield.getText()));
    }//GEN-LAST:event_eliminarprestamoActionPerformed

    private void IdprestamofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdprestamofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdprestamofieldActionPerformed

    private void idusuarioprestamofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idusuarioprestamofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idusuarioprestamofieldActionPerformed

    private void isbnlibrofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnlibrofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnlibrofieldActionPerformed

    private void telefonousuariofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonousuariofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonousuariofieldActionPerformed

    private void idusuariofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idusuariofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idusuariofieldActionPerformed

    private void eliminarusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarusuariosActionPerformed
        UsuarioController usuario= new UsuarioController();
        usuario.eliminarUsuario(Integer.parseInt(idusuariofield.getText()));
    }//GEN-LAST:event_eliminarusuariosActionPerformed

    private void leerusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerusuariosActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablausuarios.getModel();
        model.setRowCount(0);
        ArrayList<Usuario> usuarios = new ArrayList();
        UsuarioController usuario = new UsuarioController();
        List<Usuario> leer = usuario.leerUsuarios();
        usuarios.addAll(leer);

        Object columnas[] = new Object[4];
        for(Usuario c : usuarios){
            columnas[0]=c.getId_usuario();
            columnas [1]=c.getNombre();
            columnas [2]=c.getEmail();
            columnas [3]=c.getTelefono();
            model.addRow(columnas);
        }
    }//GEN-LAST:event_leerusuariosActionPerformed

    private void actualizarusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarusuariosActionPerformed
        UsuarioController usuario= new UsuarioController();
        usuario.actualizarUsuario(Integer.parseInt(idusuariofield.getText()),nombreusuariofield.getText(), emailusuariofield.getText(), Integer.parseInt(telefonousuariofield.getText()));
    }//GEN-LAST:event_actualizarusuariosActionPerformed

    private void crearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearusuarioActionPerformed
        UsuarioController usuario= new UsuarioController();
        usuario.crearUsuario(nombreusuariofield.getText(), emailusuariofield.getText(), Integer.parseInt(telefonousuariofield.getText()));
    }//GEN-LAST:event_crearusuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Idprestamofield;
    private javax.swing.JButton actualizarcategoria;
    private javax.swing.JButton actualizarlibro;
    private javax.swing.JButton actualizarprestamo;
    private javax.swing.JButton actualizarusuarios;
    private javax.swing.JTextField autorlibrofield;
    private javax.swing.JTextField añolibrofield;
    private javax.swing.JButton crearcategoria;
    private javax.swing.JButton crearlibro;
    private javax.swing.JButton crearprestamo;
    private javax.swing.JButton crearusuario;
    private javax.swing.JTextField editoriallibrofield;
    private javax.swing.JButton eliminarcategoria;
    private javax.swing.JButton eliminarlibro;
    private javax.swing.JButton eliminarprestamo;
    private javax.swing.JButton eliminarusuarios;
    private javax.swing.JTextField emailusuariofield;
    private javax.swing.JTextField fechadevolucionfield;
    private javax.swing.JTextField fechaprestamofield;
    private javax.swing.JTextField idcategoriafield;
    private javax.swing.JTextField idlibrofield;
    private javax.swing.JTextField idlibroprestamofield;
    private javax.swing.JTextField idusuariofield;
    private javax.swing.JTextField idusuarioprestamofield;
    private javax.swing.JTextField isbnlibrofield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton leercategoria;
    private javax.swing.JButton leerlibro;
    private javax.swing.JButton leerprestamos;
    private javax.swing.JButton leerusuarios;
    private javax.swing.JTextField nombrecategoriafield;
    private javax.swing.JTextField nombreusuariofield;
    private javax.swing.JTable tablacategorias;
    private javax.swing.JTable tablalibros;
    private javax.swing.JTable tablaprestamos;
    private javax.swing.JTable tablausuarios;
    private javax.swing.JTextField telefonousuariofield;
    private javax.swing.JTextField titulolibrofield;
    // End of variables declaration//GEN-END:variables
}
